test :  main.cpp src/Nodo_double.cpp src/arbol_binario.cpp  src/Nodo.cpp src/Nodo_funcion_binaria.cpp src/Nodo_funcion_unaria.cpp src/procesador_de_arbol.cpp src/Interpretador.cpp 
	g++ -std=c++11 main.cpp src/Nodo_double.cpp src/arbol_binario.cpp  src/Nodo.cpp src/Nodo_funcion_binaria.cpp src/Nodo_funcion_unaria.cpp src/procesador_de_arbol.cpp src/Interpretador.cpp -o test
